package proyectoestructuras;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nicolas
 */
public class Peliculas extends javax.swing.JFrame {

    /**
     * Creates new form Peliculas
     */
    public Peliculas() throws IOException {
        initComponents();
        leerArchivo();
    }
       ListaGenero g=new ListaGenero();
       String a="";
       String lugarImagen;
       URL url=null;
  ListaPelicula pa= new ListaPelicula(null);
  ListaPelicula pt= new ListaPelicula(null);
  ListaPelicula pc= new ListaPelicula(null);
  ListaPelicula pav= new ListaPelicula(null);
       public void leerArchivo() throws FileNotFoundException, IOException{      
BufferedReader b1;
String br;
//Accion
        b1=new BufferedReader(new FileReader("C://Users//Nicolas//Desktop//escritorio//estructura archivos//Accion.txt"));
        
        while((br=b1.readLine())!=null){         
         String []arreglo;
         arreglo=br.split(",");
         Pelicula p=new Pelicula(arreglo[0],Integer.valueOf(arreglo[1]),arreglo[2],Integer.valueOf(arreglo[3]));
         pa.Agregar(p);
    }
        b1.close();
        //Terror
        b1=new BufferedReader(new FileReader("C://Users//Nicolas//Desktop//escritorio//estructura archivos//Terror.txt"));
        while((br=b1.readLine())!=null){         
        String []arreglo;
        arreglo=br.split(",");
        Pelicula p=new Pelicula(arreglo[0],Integer.valueOf(arreglo[1]),arreglo[2],Integer.valueOf(arreglo[3]));
        pt.Agregar(p);
    }
        b1.close();
        //Comedia
       
       b1=new BufferedReader(new FileReader("C://Users//Nicolas//Desktop//escritorio//estructura archivos//Comedia.txt"));
        while((br=b1.readLine())!=null){         
        String []arreglo;
        arreglo=br.split(",");
        Pelicula p=new Pelicula(arreglo[0],Integer.valueOf(arreglo[1]),arreglo[2],Integer.valueOf(arreglo[3]));
        pc.Agregar(p);
    }
        b1.close();
        //Aventura
        b1=new BufferedReader(new FileReader("C://Users//Nicolas//Desktop//escritorio//estructura archivos//Aventura.txt"));
        while((br=b1.readLine())!=null){         
        String []arreglo;
        arreglo=br.split(",");
        Pelicula p=new Pelicula(arreglo[0],Integer.valueOf(arreglo[1]),arreglo[2],Integer.valueOf(arreglo[3]));
        pav.Agregar(p);
    }
        b1.close();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        primero = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        anteriorpelicula = new javax.swing.JButton();
        primeropelicula = new javax.swing.JButton();
        siguientepelicula = new javax.swing.JButton();
        ultimopelicula = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        mostrar = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();
        imagenpeli = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        agregar = new javax.swing.JComboBox<>();
        agregars = new javax.swing.JButton();
        botonquitar = new javax.swing.JButton();
        genero = new javax.swing.JTextField();
        botonbuscar = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        nompelicula = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        anioestreno = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Genero");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 72, 30));

        atras.setText("<");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        primero.setText("<<");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });
        jPanel1.add(primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        siguiente.setText(">");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        ultimo.setText(">>");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });
        jPanel1.add(ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        anteriorpelicula.setText("<");
        anteriorpelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorpeliculaActionPerformed(evt);
            }
        });
        jPanel1.add(anteriorpelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 350, -1, -1));

        primeropelicula.setText("<<");
        primeropelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeropeliculaActionPerformed(evt);
            }
        });
        jPanel1.add(primeropelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, -1, -1));

        siguientepelicula.setText(">");
        siguientepelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientepeliculaActionPerformed(evt);
            }
        });
        jPanel1.add(siguientepelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 350, -1, -1));

        ultimopelicula.setText(">>");
        ultimopelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimopeliculaActionPerformed(evt);
            }
        });
        jPanel1.add(ultimopelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 0, 12, -1));

        mostrar.setEditable(false);
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel1.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 134, -1));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 233, 210));
        jPanel1.add(imagenpeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 200, 280));

        descripcion.setEditable(false);
        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 240, 140));

        jTextField2.setEditable(false);
        jTextField2.setText("Seleccione una opción");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 170, 30));

        agregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar genero", "Accion ", "Terror", "Comedia ", "Aventura" }));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        agregars.setText("Mostrar");
        agregars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarsActionPerformed(evt);
            }
        });
        jPanel1.add(agregars, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        botonquitar.setText("Retirar");
        botonquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonquitarActionPerformed(evt);
            }
        });
        jPanel1.add(botonquitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, -1));
        jPanel1.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 30));

        botonbuscar.setText("buscar");
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jButton8.setText("Regresar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 40));

        jTextField4.setEditable(false);
        jTextField4.setText("Nombre");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 90, -1));

        nompelicula.setEditable(false);
        nompelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nompeliculaActionPerformed(evt);
            }
        });
        jPanel1.add(nompelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 137, -1));

        jTextField5.setEditable(false);
        jTextField5.setText("Duracion");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 80, -1));

        duracion.setEditable(false);
        duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionActionPerformed(evt);
            }
        });
        jPanel1.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 56, -1));

        jTextField1.setEditable(false);
        jTextField1.setText("Minutos");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 66, -1));

        jTextField6.setEditable(false);
        jTextField6.setText("Categoria");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 80, -1));

        categoria.setEditable(false);
        jPanel1.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 137, -1));

        jTextField7.setEditable(false);
        jTextField7.setText("Año de estreno");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 110, -1));

        anioestreno.setEditable(false);
        jPanel1.add(anioestreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 137, -1));

        jTextField3.setEditable(false);
        jTextField3.setText("Digite el genero a buscar");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, -1));

        jTextField8.setEditable(false);
        jTextField8.setText("Seleccione la opcion retirar");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, -1));

        jLabel2.setText("Pelicula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 50, 22));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoestructuras/fondo.jpg"))); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(600, 700));
        jLabel12.setMinimumSize(new java.awt.Dimension(600, 700));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed

    }//GEN-LAST:event_mostrarActionPerformed

    private void ultimopeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimopeliculaActionPerformed

  if(mostrar.getText().compareTo("Accion")==1){        
    Pelicula aux=pa.getFilme();
    while(aux.getSig()!=null){
        aux=aux.getSig();
        nompelicula.setText(aux.getNombre());
        categoria.setText(aux.getCategoria());
        duracion.setText(String.valueOf(aux.getDuracion()));
        anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
    }
        descripcion.setText("Escrita y dirigida por Lana y Lilly Wachowski"+"\n"+"y protagonizada por Keanu Reeves, Laurence Fishburne" + "\n"+", Carrie-Anne Moss y Hugo Weaving."+ "\n" + "Estrenada el 31 de marzo de 1999");
        lugarImagen="C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Accion//matrix.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Accion//matrix.jpg");
        imagenpeli.setIcon(imagen);
            }else
 if(mostrar.getText().compareTo("Terror")==0){
       Pelicula aux=pt.getFilme();
    while(aux.getSig()!=null){
        aux=aux.getSig();
        nompelicula.setText(aux.getNombre());
        categoria.setText(aux.getCategoria());
        duracion.setText(String.valueOf(aux.getDuracion()));
        anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
    }
        descripcion.setText("Es una película escrita y dirigida por"+ "\n" +"el israelí Oren Peli. El filme fue"+ "\n" +"estrenado en Estados Unidos el 14"+ "\n" +"de octubre de 2007");
        lugarImagen="C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Terror//actividad paranormal.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Terror//actividad paranormal.jpg");
        imagenpeli.setIcon(imagen);
            }else
 if(mostrar.getText().compareTo("Comedia")==1){
       Pelicula aux=pc.getFilme();
    while(aux.getSig()!=null){
        aux=aux.getSig();
        nompelicula.setText(aux.getNombre());
        categoria.setText(aux.getCategoria());
        duracion.setText(String.valueOf(aux.getDuracion()));
        anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
    }
        descripcion.setText("Ted es una película estadounidense" + "\n" +"de comedia dirigida por Seth MacFarlane y"+"\n"+"protagonizada por Mark Wahlberg, Mila"+ "\n" + "Kunis y MacFarlane.");
        lugarImagen="C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Comedia//ted.jpg.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Comedia//ted.jpg");
        imagenpeli.setIcon(imagen);
     }else
 if(mostrar.getText().compareTo("Aventura")==0){
        Pelicula aux=pav.getFilme();
    while(aux.getSig()!=null){
        aux=aux.getSig();
        nompelicula.setText(aux.getNombre());
        categoria.setText(aux.getCategoria());
        duracion.setText(String.valueOf(aux.getDuracion()));
        anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
    }
        descripcion.setText("Toy Story 3 es la tercera película"+ "\n" +" de la saga de animación Toy Story. La película ha sido distribuida en cines en formato analógico, digital y Disney Digital 3D");
        lugarImagen="C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Aventura//toy.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C://Users//Nicolas//Desktop//escritorio//imagenes peliculas//Aventura//toy.jpg");
        imagenpeli.setIcon(imagen);
        }
    }//GEN-LAST:event_ultimopeliculaActionPerformed

    private void siguientepeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientepeliculaActionPerformed
       
    if(mostrar.getText().compareTo("Accion")==1){
        ListaPelicula aux=pa;
        Pelicula g1=pa.getFilme();
        if(g1.getSig()!=null){
        pa.setFilme(g1.getSig());
        nompelicula.setText(g1.getSig().getNombre());
        categoria.setText(g1.getSig().getCategoria());
        duracion.setText(String.valueOf(g1.getSig().getDuracion()));
        anioestreno.setText(String.valueOf(g1.getSig().getAnioEstreno()));
        if(nompelicula.getText().compareTo("Rapidos y Furiosos 8")==0){
            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/rapidos y furiosos.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/rapidos y furiosos.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Película estadounidense de 2017 dirigida por"+ "\n" +"Felix Gary Gray y escrita por Chris Morgan."+"\n" + "Es la octava película de la"+"\n"+"franquicia The Fast and the Furious");
        }else
            if(nompelicula.getText().compareTo("Gladiador")==0){
            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/gladiador.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/gladiador.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Dirigida por Ridley Scott y protagonizada por" + "\n"+"Russell Crowe, Joaquin Phoenix, Connie Nielsen,"+"\n"+"Ralf Möller, Oliver Reed, Djimon Hounsou,"+"\n" +"Derek Jacobi, John Shrapnel y Richard Harris");
        }else
        if(nompelicula.getText().compareTo("Piratas del Caribe")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/piratas del caribe.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/piratas del caribe.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Es una película estadounidense de acción de 2017,"+"la quinta entrega de la exitosa serie cinematográfica"+"\n"+"Piratas del Caribe.");
        }
        else
        if(nompelicula.getText().compareTo("Matrix")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/matrix.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/matrix.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Escrita y dirigida por Lana y Lilly Wachowski"+"\n"+"y protagonizada por Keanu Reeves, Laurence Fishburne,"+"\n"+"Carrie-Anne Moss y Hugo Weaving."+"\n"+"Estrenada en los Estados Unidos el"+"\n"+"31 de marzo de 1999.");
        }
    }else
            JOptionPane.showMessageDialog(null, "Es el ultimo");
    }else
        if(mostrar.getText().compareTo("Terror")==0){
        ListaPelicula aux=pt;
        Pelicula g1=pt.getFilme();
        if(g1.getSig()!=null){
        pt.setFilme(g1.getSig());
        nompelicula.setText(g1.getSig().getNombre());
        categoria.setText(g1.getSig().getCategoria());
        duracion.setText(String.valueOf(g1.getSig().getDuracion()));
        anioestreno.setText(String.valueOf(g1.getSig().getAnioEstreno()));
        
        if(nompelicula.getText().compareTo("El Aro")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el aro.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el aro.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de terror psicológico estadounidense del año 2002,"+"\n"+"dirigida por Gore Verbinski, y protagonizada"+"\n"+"por Naomi Watts y Martin Henderson.");
         }else
        if(nompelicula.getText().compareTo("REC")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/rec.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/rec.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de terror española dirigida"+"\n"+"por Jaume Balagueró y Paco Plaza y está"+"\n"+"rodada como falso documental.");
         }else
        if(nompelicula.getText().compareTo("El Exorcismo de Emily Rose")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el exorcismo.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el exorcismo.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de terror dirigida por Scott Derrickson,"+"\n"+"basada en la verdadera historia de Anneliese Michel,"+"\n"+"y protagonizada por Tom Wilkinson, Laura Linney"+"\n"+"y Jennifer Carpenter");
        }else
        if(nompelicula.getText().compareTo("Actividad Paranormal")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/actividad paranormal.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/actividad paranormal.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película escrita y dirigida"+"\n" +"por el israelí Oren Peli.");
         }
    }else
            JOptionPane.showMessageDialog(null, "Es el ultimo");
    }else
        if(mostrar.getText().compareTo("Comedia")==1){
        ListaPelicula aux=pc;
        Pelicula g1=pc.getFilme();
        if(g1.getSig()!=null){
        pc.setFilme(g1.getSig());
        nompelicula.setText(g1.getSig().getNombre());
        categoria.setText(g1.getSig().getCategoria());
        duracion.setText(String.valueOf(g1.getSig().getDuracion()));
        anioestreno.setText(String.valueOf(g1.getSig().getAnioEstreno()));
        
        if(nompelicula.getText().compareTo("Mi Villano Favorito 2")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/villano.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/villano.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película animada estrenada el 5 de julio de 2013."+"\n"+"Se trata de la secuela de Mi Villano Favorito.");
        }else
        if(nompelicula.getText().compareTo("Focus")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/focus.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/focus.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Escrita y dirigida por Glenn Ficarra y John Requa."+"\n"+"Es protagonizada por Will Smith, Margot Robbie,"+"\n"+"y Rodrigo Santoro");
        }else
        if(nompelicula.getText().compareTo("Hombres de Negro 3")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/hombresn.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/hombresn.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película dirigida por Barry Sonnenfeld"+"\n"+"y protagonizada por Will Smith, Tommy Lee Jones"+"\n"+"y Josh Brolin.");
        }else
        if(nompelicula.getText().compareTo("TED")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/ted.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/ted.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película estadounidense de comedia"+"\n"+"dirigida por Seth MacFarlane y protagonizada"+"\n"+"por Mark Wahlberg, Mila Kunis y MacFarlane.");
        }
    }else
            JOptionPane.showMessageDialog(null, "Es el ultimo");
    }else
        if(mostrar.getText().compareTo("Aventura")==0){
        ListaPelicula aux=pav;
        Pelicula g1=pav.getFilme();
        if(g1.getSig()!=null){
        pav.setFilme(g1.getSig());
        nompelicula.setText(g1.getSig().getNombre());
        categoria.setText(g1.getSig().getCategoria());
        duracion.setText(String.valueOf(g1.getSig().getDuracion()));
        anioestreno.setText(String.valueOf(g1.getSig().getAnioEstreno()));
       
        if(nompelicula.getText().compareTo("La momia")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/momia.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/momia.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de aventuras estadounidense de 1999,"+"\n"+"rodada, escrita y dirigida por Stephen Sommers"+"\n"+"e interpretada por Brendan Fraser, Rachel Weisz,"+"\n"+"John Hannah y Kevin J. O'Connor, con Arnold Vosloo"+"\n"+"en el papel principal como la momia reencarnada.");
        }else
             if(nompelicula.getText().compareTo("xXx Reactivado")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/reactivo.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/reactivo.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película estadounidense de acción y"+"\n"+"aventuras dirigida por D.J. Caruso, producida por Vin Diesel,"+"\n"+"Neal H. Moritz, Joe Roth, Jeff Kirschenbaum y"+"\n"+"Samantha Vincent y escrita por F. Scott Frazier y Chad St. John.");
             }else
         if(nompelicula.getText().compareTo("El rey Leon")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/leon.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/leon.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película animada producida por Walt Disney Feature Animation"+"\n"+"y distribuida por Walt Disney Pictures. ");
        }else
            if(nompelicula.getText().compareTo("Toy Story 3")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/toy.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/toy.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es la tercera película de la saga de animación Toy Story."+"\n"+"La película ha sido distribuida en cines en formato analógico,"+"\n"+"digital y Disney Digital 3D");
        }
    }else
            JOptionPane.showMessageDialog(null, "Es el ultimo");
    }
    }//GEN-LAST:event_siguientepeliculaActionPerformed

    private void primeropeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeropeliculaActionPerformed
if(mostrar.getText().compareTo("Accion")==1){
   Pelicula aux=pa.getFilme();
   nompelicula.setText(aux.getNombre());
   categoria.setText(aux.getCategoria());
   duracion.setText(String.valueOf(aux.getDuracion()));
   anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
   
   lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
   imagenpeli.setIcon(imagen);
   descripcion.setText("Es una película estadounidense de 2017 y"+"\n"+"la última de la trilogía de Wolverine,"+"\n"+"basada en el personaje de Wolverine,"+"\n"+"de Marvel Comics, y producida por la 20th Century Fox");
}else
    if(mostrar.getText().compareTo("Terror")==0){
   Pelicula aux=pt.getFilme();
    nompelicula.setText(aux.getNombre());
   categoria.setText(aux.getCategoria());
   duracion.setText(String.valueOf(aux.getDuracion()));
   anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
   
   lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
   imagenpeli.setIcon(imagen);
   descripcion.setText("Es una película de terror de 2013 dirigida por James Wan"+"\n"+"y protagonizada por Vera Farmiga y Patrick Wilson"+"\n"+"en el papel de los parapsicólogos Lorraine y Ed Warren");
    }else
   if(mostrar.getText().compareTo("Comedia")==1){
   Pelicula aux=pc.getFilme();
    nompelicula.setText(aux.getNombre());
   categoria.setText(aux.getCategoria());
   duracion.setText(String.valueOf(aux.getDuracion()));
   anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
   
   lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
   imagenpeli.setIcon(imagen);
   descripcion.setText("Es una película estadounidense estrenada en 2012 del género de comedia slapstick,"+"\n"+"basada en la popular serie de cortos de mediados del siglo XX,"+"\n"+"realizada por el trío cómico \"Los tres chiflados\".");
   }else
       if(mostrar.getText().compareTo("Aventura")==0){
   Pelicula aux=pav.getFilme();
    nompelicula.setText(aux.getNombre());
   categoria.setText(aux.getCategoria());
   duracion.setText(String.valueOf(aux.getDuracion()));
   anioestreno.setText(String.valueOf(aux.getAnioEstreno()));
   
   lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
   imagenpeli.setIcon(imagen);
    descripcion.setText("Es una película estadounidense de acción, fantasía, monstruos y"+"\n"+"aventuras dirigida por Jordan Vogt-Roberts. Es el reinicio de la franquicia"+"\n"+"King Kong y servirá como la segunda entrega del Monstruoverso de Legendary");
       }
    }//GEN-LAST:event_primeropeliculaActionPerformed

    private void anteriorpeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorpeliculaActionPerformed
        String m=mostrar.getText();
        if(m.compareTo("Accion")==1){
            Pelicula gn=pa.getFilme();
            if(gn.getAnt()!=null){
                nompelicula.setText(gn.getAnt().getNombre());
                duracion.setText(String.valueOf(gn.getAnt().getDuracion()));
                categoria.setText(gn.getAnt().getCategoria());
                anioestreno.setText(String.valueOf(gn.getAnt().getAnioEstreno()));
                pa.setFilme(gn.getAnt());
                if(nompelicula.getText().compareTo("Logan")==0){
            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Es una película estadounidense de 2017 y"+"\n"+"la última de la trilogía de Wolverine,"+"\n"+"basada en el personaje de Wolverine,"+"\n"+"de Marvel Comics, y producida por la 20th Century Fox");
        }        
                if(nompelicula.getText().compareTo("Rapidos y Furiosos 8")==0){
            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/rapidos y furiosos.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/rapidos y furiosos.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Película estadounidense de 2017 dirigida por"+ "\n" +"Felix Gary Gray y escrita por Chris Morgan."+"\n" + "Es la octava película de la"+"\n"+"franquicia The Fast and the Furious");
       
        }else
            if(nompelicula.getText().compareTo("Gladiador")==0){
            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/gladiador.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/gladiador.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Dirigida por Ridley Scott y protagonizada por" + "\n"+"Russell Crowe, Joaquin Phoenix, Connie Nielsen,"+"\n"+"Ralf Möller, Oliver Reed, Djimon Hounsou,"+"\n" +"Derek Jacobi, John Shrapnel y Richard Harris");

        }else
        if(nompelicula.getText().compareTo("Piratas del Caribe")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/piratas del caribe.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagens1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/piratas del caribe.jpg");
        imagenpeli.setIcon(imagens1);
        descripcion.setText("Es una película estadounidense de acción de 2017,"+"la quinta entrega de la exitosa serie cinematográfica"+"\n"+"Piratas del Caribe.");

        }
            }else
                    JOptionPane.showMessageDialog(null, " Es el primero");
        }else
            if(m.compareTo("Terror")==0){
                Pelicula g1=pt.getFilme();
                if(g1.getAnt()!=null){
                    nompelicula.setText(g1.getAnt().getNombre());
                    duracion.setText(String.valueOf(g1.getAnt().getDuracion()));
                    categoria.setText(g1.getAnt().getCategoria());
                    anioestreno.setText(String.valueOf(g1.getAnt().getAnioEstreno()));
                    pt.setFilme(g1.getAnt());
          if(nompelicula.getText().compareTo("El Conjuro")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de terror de 2013 dirigida por James Wan"+"\n"+"y protagonizada por Vera Farmiga y Patrick Wilson"+"\n"+"en el papel de los parapsicólogos Lorraine y Ed Warren");

         }else          
              if(nompelicula.getText().compareTo("El Aro")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el aro.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el aro.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de terror psicológico estadounidense del año 2002,"+"\n"+"dirigida por Gore Verbinski, y protagonizada"+"\n"+"por Naomi Watts y Martin Henderson.");

         }else
        if(nompelicula.getText().compareTo("REC")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/rec.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/rec.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de terror española dirigida"+"\n"+"por Jaume Balagueró y Paco Plaza y está"+"\n"+"rodada como falso documental.");

         }else
        if(nompelicula.getText().compareTo("El Exorcismo de Emily Rose")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el exorcismo.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el exorcismo.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de terror dirigida por Scott Derrickson,"+"\n"+"basada en la verdadera historia de Anneliese Michel,"+"\n"+"y protagonizada por Tom Wilkinson, Laura Linney"+"\n"+"y Jennifer Carpenter");

         }
            }else
                    JOptionPane.showMessageDialog(null, " Es el primero");
            }else
        if(m.compareTo("Comedia")==1){
                Pelicula g1=pc.getFilme();
                if(g1.getAnt()!=null){
                    nompelicula.setText(g1.getAnt().getNombre());
                    duracion.setText(String.valueOf(g1.getAnt().getDuracion()));
                    categoria.setText(g1.getAnt().getCategoria());
                    anioestreno.setText(String.valueOf(g1.getAnt().getAnioEstreno()));
                    pc.setFilme(g1.getAnt());
                    
        if(nompelicula.getText().compareTo("Los tres Chiflados")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película estadounidense estrenada en 2012 del género de comedia slapstick,"+"\n"+"basada en la popular serie de cortos de mediados del siglo XX,"+"\n"+"realizada por el trío cómico \"Los tres chiflados\".");

        }else
                    if(nompelicula.getText().compareTo("Mi Villano Favorito 2")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/villano.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/villano.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película animada estrenada el 5 de julio de 2013."+"\n"+"Se trata de la secuela de Mi Villano Favorito.");

        }else
        if(nompelicula.getText().compareTo("Focus")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/focus.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/focus.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Escrita y dirigida por Glenn Ficarra y John Requa."+"\n"+"Es protagonizada por Will Smith, Margot Robbie,"+"\n"+"y Rodrigo Santoro");

        }else
        if(nompelicula.getText().compareTo("Hombres de Negro 3")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/hombresn.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/hombresn.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película dirigida por Barry Sonnenfeld"+"\n"+"y protagonizada por Will Smith, Tommy Lee Jones"+"\n"+"y Josh Brolin.");
        }
            }else
                    JOptionPane.showMessageDialog(null, " Es el primero");
        }else
            if(m.compareTo("Aventura")==0){
                Pelicula g1=pav.getFilme();
                if(g1.getAnt()!=null){
                    nompelicula.setText(g1.getAnt().getNombre());
                    duracion.setText(String.valueOf(g1.getAnt().getDuracion()));
                    categoria.setText(g1.getAnt().getCategoria());
                    anioestreno.setText(String.valueOf(g1.getAnt().getAnioEstreno()));
                    pav.setFilme(g1.getAnt());    
                    
        if(nompelicula.getText().compareTo("Kong La Isla Calavera")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película estadounidense de acción, fantasía, monstruos y"+"\n"+"aventuras dirigida por Jordan Vogt-Roberts. Es el reinicio de la franquicia"+"\n"+"King Kong y servirá como la segunda entrega del Monstruoverso de Legendary");

        }else
        if(nompelicula.getText().compareTo("La momia")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/momia.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/momia.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película de aventuras estadounidense de 1999,"+"\n"+"rodada, escrita y dirigida por Stephen Sommers"+"\n"+"e interpretada por Brendan Fraser, Rachel Weisz,"+"\n"+"John Hannah y Kevin J. O'Connor, con Arnold Vosloo"+"\n"+"en el papel principal como la momia reencarnada.");

        }else
             if(nompelicula.getText().compareTo("xXx Reactivado")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/reactivo.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/reactivo.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película estadounidense de acción y"+"\n"+"aventuras dirigida por D.J. Caruso, producida por Vin Diesel,"+"\n"+"Neal H. Moritz, Joe Roth, Jeff Kirschenbaum y"+"\n"+"Samantha Vincent y escrita por F. Scott Frazier y Chad St. John.");

             }else
         if(nompelicula.getText().compareTo("El rey Leon")==0){
        lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/leon.jpg";
        url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/leon.jpg");
        imagenpeli.setIcon(imagen);
        descripcion.setText("Es una película animada producida por Walt Disney Feature Animation"+"\n"+"y distribuida por Walt Disney Pictures. ");

        }
            }else
                    JOptionPane.showMessageDialog(null, " Es el primero");
            }
    }//GEN-LAST:event_anteriorpeliculaActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed

        Genero aux=g.getTipo();
        while(aux.getSig()!=null){
            aux=aux.getSig();
            mostrar.setText(aux.getNombre());
        }
   if(mostrar.getText().compareTo("Accion")==1){
    nompelicula.setText(pa.getFilme().getNombre());
   categoria.setText(pa.getFilme().getCategoria());
   duracion.setText(String.valueOf(pa.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pa.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg");
   fondo.setIcon(imagen);
   
   lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense de 2017 y"+"\n"+"la última de la trilogía de Wolverine,"+"\n"+"basada en el personaje de Wolverine,"+"\n"+"de Marvel Comics, y producida por la 20th Century Fox");

}else
    if(mostrar.getText().compareTo("Terror")==0){
    nompelicula.setText(pt.getFilme().getNombre());
   categoria.setText(pt.getFilme().getCategoria());
   duracion.setText(String.valueOf(pt.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pt.getFilme().getAnioEstreno()));
   descripcion.setText("kfmvfslkvnkfvndflkvnldfk");
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png");
   fondo.setIcon(imagen);
   
    lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película de terror de 2013 dirigida por James Wan"+"\n"+"y protagonizada por Vera Farmiga y Patrick Wilson"+"\n"+"en el papel de los parapsicólogos Lorraine y Ed Warren");

    }else
   if(mostrar.getText().compareTo("Comedia")==1){
    nompelicula.setText(pc.getFilme().getNombre());
   categoria.setText(pc.getFilme().getCategoria());
   duracion.setText(String.valueOf(pc.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pc.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense estrenada en 2012 del género de comedia slapstick,"+"\n"+"basada en la popular serie de cortos de mediados del siglo XX,"+"\n"+"realizada por el trío cómico \"Los tres chiflados\".");

   }else
       if(mostrar.getText().compareTo("Aventura")==0){
    nompelicula.setText(pav.getFilme().getNombre());
   categoria.setText(pav.getFilme().getCategoria());
   duracion.setText(String.valueOf(pav.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pav.getFilme().getAnioEstreno()));
   
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png");
   fondo.setIcon(imagen);
   
   lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
   imagenpeli.setIcon(imagen1);
    descripcion.setText("Es una película estadounidense de acción, fantasía, monstruos y"+"\n"+"aventuras dirigida por Jordan Vogt-Roberts. Es el reinicio de la franquicia"+"\n"+"King Kong y servirá como la segunda entrega del Monstruoverso de Legendary");

       }
    }//GEN-LAST:event_ultimoActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        ListaGenero aux=g;
        Genero g1=g.getTipo();
        if(g1.getSig()!=null){
            g.setTipo(g1.getSig());
            mostrar.setText(g1.getSig().getNombre());
            if(g1.getSig()==null){
             JOptionPane.showMessageDialog(null, "Es el ultimo");
            }
        }
   if(mostrar.getText().compareTo("Accion")==1){
    nompelicula.setText(pa.getFilme().getNombre());
   categoria.setText(pa.getFilme().getCategoria());
   duracion.setText(String.valueOf(pa.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pa.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense de 2017 y"+"\n"+"la última de la trilogía de Wolverine,"+"\n"+"basada en el personaje de Wolverine,"+"\n"+"de Marvel Comics, y producida por la 20th Century Fox");

}else
    if(mostrar.getText().compareTo("Terror")==0){
    nompelicula.setText(pt.getFilme().getNombre());
   categoria.setText(pt.getFilme().getCategoria());
   duracion.setText(String.valueOf(pt.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pt.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película de terror de 2013 dirigida por James Wan"+"\n"+"y protagonizada por Vera Farmiga y Patrick Wilson"+"\n"+"en el papel de los parapsicólogos Lorraine y Ed Warren");

    }else
   if(mostrar.getText().compareTo("Comedia")==1){
    nompelicula.setText(pc.getFilme().getNombre());
   categoria.setText(pc.getFilme().getCategoria());
   duracion.setText(String.valueOf(pc.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pc.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense estrenada en 2012 del género de comedia slapstick,"+"\n"+"basada en la popular serie de cortos de mediados del siglo XX,"+"\n"+"realizada por el trío cómico \"Los tres chiflados\".");

   }else
   if(mostrar.getText().compareTo("Aventura")==0){
   nompelicula.setText(pav.getFilme().getNombre());
   categoria.setText(pav.getFilme().getCategoria());
   duracion.setText(String.valueOf(pav.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pav.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png");
   fondo.setIcon(imagen);
   
   lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
   imagenpeli.setIcon(imagen1);
    descripcion.setText("Es una película estadounidense de acción, fantasía, monstruos y"+"\n"+"aventuras dirigida por Jordan Vogt-Roberts. Es el reinicio de la franquicia"+"\n"+"King Kong y servirá como la segunda entrega del Monstruoverso de Legendary");

       }

    }//GEN-LAST:event_siguienteActionPerformed

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
   mostrar.setText(g.getTipo().getNombre());
   if(mostrar.getText().compareTo("Accion")==1){
    nompelicula.setText(pa.getFilme().getNombre());
   categoria.setText(pa.getFilme().getCategoria());
   duracion.setText(String.valueOf(pa.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pa.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg");
   fondo.setIcon(imagen);
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense de 2017 y"+"\n"+"la última de la trilogía de Wolverine,"+"\n"+"basada en el personaje de Wolverine,"+"\n"+"de Marvel Comics, y producida por la 20th Century Fox");

}else
    if(mostrar.getText().compareTo("Terror")==0){
    nompelicula.setText(pt.getFilme().getNombre());
   categoria.setText(pt.getFilme().getCategoria());
   duracion.setText(String.valueOf(pt.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pt.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película de terror de 2013 dirigida por James Wan"+"\n"+"y protagonizada por Vera Farmiga y Patrick Wilson"+"\n"+"en el papel de los parapsicólogos Lorraine y Ed Warren");

    }else
   if(mostrar.getText().compareTo("Comedia")==1){
    nompelicula.setText(pc.getFilme().getNombre());
   categoria.setText(pc.getFilme().getCategoria());
   duracion.setText(String.valueOf(pc.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pc.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense estrenada en 2012 del género de comedia slapstick,"+"\n"+"basada en la popular serie de cortos de mediados del siglo XX,"+"\n"+"realizada por el trío cómico \"Los tres chiflados\".");

   }else
       if(mostrar.getText().compareTo("Aventura")==0){
   Pelicula aux1=pav.getFilme();
    nompelicula.setText(aux1.getNombre());
   categoria.setText(aux1.getCategoria());
   duracion.setText(String.valueOf(aux1.getDuracion()));
   anioestreno.setText(String.valueOf(aux1.getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
   imagenpeli.setIcon(imagen1);
    descripcion.setText("Es una película estadounidense de acción, fantasía, monstruos y"+"\n"+"aventuras dirigida por Jordan Vogt-Roberts. Es el reinicio de la franquicia"+"\n"+"King Kong y servirá como la segunda entrega del Monstruoverso de Legendary");

       }
    }//GEN-LAST:event_primeroActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        ListaGenero aux=g;
        Genero g1=aux.getTipo();
        if(g1.getAnt()!=null){
            g.setTipo(g1.getAnt());
            mostrar.setText(g1.getAnt().getNombre());
        }
   if(mostrar.getText().compareTo("Accion")==1){
    nompelicula.setText(  pa.getFilme().getNombre());
   categoria.setText(  pa.getFilme().getCategoria());
   duracion.setText(String.valueOf(  pa.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(  pa.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense de 2017 y"+"\n"+"la última de la trilogía de Wolverine,"+"\n"+"basada en el personaje de Wolverine,"+"\n"+"de Marvel Comics, y producida por la 20th Century Fox");

}else
    if(mostrar.getText().compareTo("Terror")==0){
    nompelicula.setText(pt.getFilme().getNombre());
   categoria.setText(pt.getFilme().getCategoria());
   duracion.setText(String.valueOf(pt.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pt.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro1.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película de terror de 2013 dirigida por James Wan"+"\n"+"y protagonizada por Vera Farmiga y Patrick Wilson"+"\n"+"en el papel de los parapsicólogos Lorraine y Ed Warren");

    }else
   if(mostrar.getText().compareTo("Comedia")==1){
    nompelicula.setText(pc.getFilme().getNombre());
   categoria.setText(pc.getFilme().getCategoria());
   duracion.setText(String.valueOf(pc.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pc.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense estrenada en 2012 del género de comedia slapstick,"+"\n"+"basada en la popular serie de cortos de mediados del siglo XX,"+"\n"+"realizada por el trío cómico \"Los tres chiflados\".");

   }else
       if(mostrar.getText().compareTo("Aventura")==0){
    nompelicula.setText(pav.getFilme().getNombre());
   categoria.setText(pav.getFilme().getCategoria());
   duracion.setText(String.valueOf(pav.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pav.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
   imagenpeli.setIcon(imagen1);
    descripcion.setText("Es una película estadounidense de acción, fantasía, monstruos y"+"\n"+"aventuras dirigida por Jordan Vogt-Roberts. Es el reinicio de la franquicia"+"\n"+"King Kong y servirá como la segunda entrega del Monstruoverso de Legendary");

       }

    }//GEN-LAST:event_atrasActionPerformed

    private void nompeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nompeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nompeliculaActionPerformed

    private void duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Ventana1 v=new Ventana1();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
        Genero aux=g.getTipo();
        if(g.esVacia()==true){
             JOptionPane.showMessageDialog(null,"Agregue generos");
        }else
        if(aux.getSig()==null){
                 if(g.buscar(g.getTipo().getNombre())==true){
                JOptionPane.showMessageDialog(null,"El genero se encuentra disponible");
            }else
                JOptionPane.showMessageDialog(null,"El genero no se encuentra disponible");
        }else
        if(aux.getSig()!=null){
             if(g.buscar(genero.getText())==false){
            JOptionPane.showMessageDialog(null,"El genero no se encuentra disponible");
             }else
        if(g.buscar(genero.getText())==true){ 
            JOptionPane.showMessageDialog(null,"El genero se encuentra disponible");
        }
              
            }
    }//GEN-LAST:event_botonbuscarActionPerformed

    private void botonquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonquitarActionPerformed
     if(g.esVacia()==true){
            JOptionPane.showMessageDialog(null,"Primero agrege generos");
        }else
        if(g.getTipo().getSig()==null){
            JOptionPane.showMessageDialog(null,"Debe existir por lo menos un genero en esta lista");
        }else
        if(g.esVacia()==false){
            try {
                Genero aux=g.getTipo();
                g.quitar(g.getTipo().getNombre());
                JOptionPane.showMessageDialog(null,"El genero se retiro con exito");
                System.out.println(g);
    mostrar.setText(aux.getSig().getNombre());
   if(mostrar.getText().compareTo("Accion")==1){
   nompelicula.setText(  pa.getFilme().getNombre());
   categoria.setText(  pa.getFilme().getCategoria());
   duracion.setText(String.valueOf(  pa.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(  pa.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg");
   fondo.setIcon(imagen);
   
    lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense de 2017 y"+"\n"+"la última de la trilogía de Wolverine,"+"\n"+"basada en el personaje de Wolverine,"+"\n"+"de Marvel Comics, y producida por la 20th Century Fox");

}else
    if(mostrar.getText().compareTo("Terror")==0){
    nompelicula.setText(pt.getFilme().getNombre());
   categoria.setText(pt.getFilme().getCategoria());
   duracion.setText(String.valueOf(pt.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pt.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png");
   fondo.setIcon(imagen);
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película de terror de 2013 dirigida por James Wan"+"\n"+"y protagonizada por Vera Farmiga y Patrick Wilson"+"\n"+"en el papel de los parapsicólogos Lorraine y Ed Warren");

    }else
   if(mostrar.getText().compareTo("Comedia")==1){
    nompelicula.setText(pc.getFilme().getNombre());
   categoria.setText(pc.getFilme().getCategoria());
   duracion.setText(String.valueOf(pc.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pc.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg");
   fondo.setIcon(imagen);
   
   
      lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
   imagenpeli.setIcon(imagen1);
   descripcion.setText("Es una película estadounidense estrenada en 2012 del género de comedia slapstick,"+"\n"+"basada en la popular serie de cortos de mediados del siglo XX,"+"\n"+"realizada por el trío cómico \"Los tres chiflados\".");

   }else
       if(mostrar.getText().compareTo("Aventura")==0){
    nompelicula.setText(pav.getFilme().getNombre());
   categoria.setText(pav.getFilme().getCategoria());
   duracion.setText(String.valueOf(pav.getFilme().getDuracion()));
   anioestreno.setText(String.valueOf(pav.getFilme().getAnioEstreno()));
   lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png");
   fondo.setIcon(imagen);
   
     lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
   url=this.getClass().getResource(lugarImagen);
   ImageIcon imagen1=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
   imagenpeli.setIcon(imagen1);
    descripcion.setText("Es una película estadounidense de acción, fantasía, monstruos y"+"\n"+"aventuras dirigida por Jordan Vogt-Roberts. Es el reinicio de la franquicia"+"\n"+"King Kong y servirá como la segunda entrega del Monstruoverso de Legendary");
       }
                
            } catch (Exception ex) {
                Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonquitarActionPerformed

    private void agregarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarsActionPerformed
        Genero g1 = new Genero(a);
        g.Agregar(g1);
        mostrar.setText(a);
        System.out.println(g.toString());
        if(a.compareTo("Accion")==1){
            nompelicula.setText(pa.getFilme().getNombre());
            categoria.setText(pa.getFilme().getCategoria());
            duracion.setText(String.valueOf(pa.getFilme().getDuracion()));
            anioestreno.setText(String.valueOf(pa.getFilme().getAnioEstreno()));
            lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.png";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/accions.jpg");
            fondo.setIcon(imagen);

            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagenp=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Accion/logan.jpg");
            imagenpeli.setIcon(imagenp);
            descripcion.setText("Pelicula estadounidense y la ultima" + "\n"+ "trilogia de wolverine. Fue producida" + "\n" + "por la 20th Century Fox");
        }else
        if(a.compareTo("Terror")==0){
            nompelicula.setText(pt.getFilme().getNombre());
            categoria.setText(pt.getFilme().getCategoria());
            duracion.setText(String.valueOf(pt.getFilme().getDuracion()));
            anioestreno.setText(String.valueOf(pt.getFilme().getAnioEstreno()));
            descripcion.setText("kfmvfslkvnkfvndflkvnldfk");
            lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/terror1.png");
            fondo.setIcon(imagen);

            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagenp=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Terror/el conjuro.jpg");
            imagenpeli.setIcon(imagenp);
            descripcion.setText("Dirigida por James Wan y protagonizada" + "\n" + "por Vera Farmiga y Patric Wilson");
        }else
        if(a.compareTo("Comedia")==1){
            nompelicula.setText(pc.getFilme().getNombre());
            categoria.setText(pc.getFilme().getCategoria());
            duracion.setText(String.valueOf(pc.getFilme().getDuracion()));
            anioestreno.setText(String.valueOf(pc.getFilme().getAnioEstreno()));
            descripcion.setText("kfmvfslkvnkfvndflkvnldfk");
            lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/comedia.jpg");
            fondo.setIcon(imagen);

            descripcion.setText("kfmvfslkvnkfvndflkvnldfk");
            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagenp=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Comedia/los chiflados.jpg");
            imagenpeli.setIcon(imagenp);
        }
        else
        if(a.compareTo("Aventura")==0){
            nompelicula.setText(pav.getFilme().getNombre());
            categoria.setText(pav.getFilme().getCategoria());
            duracion.setText(String.valueOf(pav.getFilme().getDuracion()));
            anioestreno.setText(String.valueOf(pav.getFilme().getAnioEstreno()));
            descripcion.setText("kfmvfslkvnkfvndflkvnldfk");
            lugarImagen="C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagen=new ImageIcon("C:/Users/Nicolas/Desktop/imgenes poyecto estructuras/aventura1.png");
            fondo.setIcon(imagen);

            descripcion.setText("kfmvfslkvnkfvndflkvnldfk");
            lugarImagen="C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg";
            url=this.getClass().getResource(lugarImagen);
            ImageIcon imagenp=new ImageIcon("C:/Users/Nicolas/Desktop/escritorio/imagenes peliculas/Aventura/kong.jpg");
            imagenpeli.setIcon(imagenp);
        }

    }//GEN-LAST:event_agregarsActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        a=agregar.getSelectedItem().toString();
        if(a.compareTo("Agregar genero")==0){
            JOptionPane.showMessageDialog(rootPane, " Seleccione un genero valido");
        }
        System.out.println(a);
    }//GEN-LAST:event_agregarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Peliculas().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Peliculas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> agregar;
    private javax.swing.JButton agregars;
    private javax.swing.JTextField anioestreno;
    private javax.swing.JButton anteriorpelicula;
    private javax.swing.JButton atras;
    private javax.swing.JButton botonbuscar;
    private javax.swing.JButton botonquitar;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextField duracion;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField genero;
    private javax.swing.JLabel imagenpeli;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField mostrar;
    private javax.swing.JTextField nompelicula;
    private javax.swing.JButton primero;
    private javax.swing.JButton primeropelicula;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton siguientepelicula;
    private javax.swing.JButton ultimo;
    private javax.swing.JButton ultimopelicula;
    // End of variables declaration//GEN-END:variables
}
